FROM payara/server-full:6.2024.10-jdk21


ENV PAYARA_ARGS --debug

ARG OPEN_API_KEY

ENV OPEN_API_KEY=${OPEN_API_KEY}
ENV S3_BUCKET_ACCESS_KEY=${S3_BUCKET_ACCESS_KEY}
ENV S3_BUCKET_SECRET_KEY=${S3_BUCKET_SECRET_KEY}
ENV AWS_S3_BUCKET_ACCESS_KEY=${AWS_S3_BUCKET_ACCESS_KEY}
ENV AWS_S3_BUCKET_SECRET_KEY=${AWS_S3_BUCKET_SECRET_KEY}
COPY target/*.war ${DEPLOY_DIR}

EXPOSE 8080
EXPOSE 4848
EXPOSE 9009




