version: '3.9'
services:
  app:
    image: fish.payara/jakarta-gpt-21
    environment:
      OPEN_API_KEY: ${OPEN_API_KEY}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SERVER: ${DB_SERVER}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_URL: ${DB_URL}
    volumes:
      - ./deployments:/opt/payara/appserver/glassfish/domains/domain1/autodeploy
    ports:
      - "8080:8080"
      - "4848:4848"
      - "9009:9009"
    restart: always
    healthcheck:
      test: curl --fail http://localhost:8080/health/ready || exit 1
    build:
      context: .
      dockerfile: Dockerfile
