version: '3'

services:
  jenkins:
    build: .
    user: root
    environment:
      JENKINS_ADMIN_ID: ${JENKINS_ADMIN_ID}
      JENKINS_ADMIN_PASSWORD: ${JENKINS_ADMIN_PASSWORD}
      GITHUB_USERNAME: ${GITHUB_USERNAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins.yaml:/jenkins_configs/jenkins.yaml
      - ./jenkins_home:/var/jenkins_home
    restart: unless-stopped