name: OPG Release Pipeline

on:
  # manually
  workflow_dispatch:
  # on any push to master branch
  #push:
  #  branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Verify
        run: mvn -B -ntp verify
      - name: Prepare release version
        run: mvn -B -ntp versions:set -DremoveSnapshot -DgenerateBackupPoms=false
      - name: commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "[bot] prepare release version"
          git push
      - name: Build Artifacts
        run: |
          mvn -B -ntp clean package
      - name: Release
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B -ntp -N jreleaser:release
      - name: Login to image registry
        uses: docker/login-action@v3.0.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: docker push ghcr.io/ghazyami/hello-world:latest
      - name: Prepare next development cycle
        run: mvn -B -ntp versions:set -DnextSnapshot -DgenerateBackupPoms=false
      - name: commit and push
        run: |
          git commit -am "[bot] prepare next development version"
          git push
