#name: Build and Push to Docker Hub
#
#on:
#  push:
#    branches: [ "main", "migrate-to-jsf" ]
#  pull_request:
#    branches: [ "main" ]
#jobs:
#  build-and-push:
#    runs-on: ubuntu-latest
#    env:
#      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/jee-gpt:latest
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up JDK 21
#        uses: actions/setup-java@v3
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#          cache: maven
#
#      - name: Build with Maven
#        run: mvn clean package  -DskipTests
#
#      - name: Test with Maven
#        run: mvn test
#
#      - name: Build Docker Image
#        if: success()
#
#        run: |
#          docker build --build-arg OPEN_API_KEY=${{ secrets.OPEN_API_KEY }} -t ${{ env.IMAGE_NAME }} .
#
#      - name: Log in to Docker Hub
#        if: success()
#        uses: docker/login-action@v1
#        with:
##          registry: your-private-registry.com
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Push Image to Docker Hub
#        if: success()
#        run: |
#          docker push ${{ env.IMAGE_NAME }}
