name: Build and Push To Payara Cloud

on:
  push:
    branches: [ "cloud-postgres" ]
  pull_request:
    branches: [ "cloud-postgres" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run:  mvn clean package -Pproduction  -DskipTests

      - name: Test with Maven
        run: mvn test

      - name: Download Payara Cloud CLI
        if: success()
        run: |
          wget https://nexus.payara.fish/repository/payara-artifacts/fish/payara/cloud/pcl/1.1.0/pcl-1.1.0.jar -O pcl.jar
          chmod +x pcl.jar

      - name: Deploy to Payara Cloud
        if: success()
        env:
          PCL_AUTH_TOKEN: ${{ secrets.PCL_AUTH_TOKEN }}
        run: |
          java -jar pcl.jar -n live-demo-dev upload -a jee-gpt-jdk21 target/*.war
